import type { Card } from "./types";

// Board positions referenced by movement cards.
// 0 GO · 15 Allama Iqbal Airport · 27 Gwadar · 29 Murree · 31 Islamabad · 32 Lahore · 34 Karachi · 39 DHA Lahore

/** Qismat — the "Chance"-style deck. More movement & business events. */
export const QISMAT: Card[] = [
  { id: "q1", text: "Overseas remittance received. Collect Rs. 15.", effect: { kind: "collect", amount: 15 } },
  { id: "q2", text: "Freelance client paid early. Collect Rs. 100.", effect: { kind: "collect", amount: 100 } },
  { id: "q3", text: "Car engine failure. Pay Rs. 75.", effect: { kind: "pay", amount: 75 } },
  { id: "q4", text: "Import duties increased. Pay Rs. 50.", effect: { kind: "pay", amount: 50 } },
  { id: "q5", text: "Advance to Karachi, the City of Lights. If you pass GO, collect your salary.", effect: { kind: "moveTo", pos: 34, awardGo: true } },
  { id: "q6", text: "Advance to Islamabad, the planned capital.", effect: { kind: "moveTo", pos: 31, awardGo: true } },
  { id: "q7", text: "Property market boom — collect Rs. 25 rent from every player.", effect: { kind: "collectFromEach", amount: 25 } },
  { id: "q8", text: "Utility bills rise. Pay Rs. 40 per developed plot and Rs. 115 per Corporate Tower.", effect: { kind: "repairs", perStageEarly: 40, perTower: 115 } },
  { id: "q9", text: "Won a government contract. Collect Rs. 150.", effect: { kind: "collect", amount: 150 } },
  { id: "q10", text: "Tax refund received from the FBR. Collect Rs. 60.", effect: { kind: "collect", amount: 60 } },
  { id: "q11", text: "NAB summons! Go directly to Central Lockup. Do not pass GO.", effect: { kind: "goToJail" } },
  { id: "q12", text: "Released by court order. Keep this card until needed.", effect: { kind: "jailFree" } },
  { id: "q13", text: "Advance to GO — Salary Day. Collect Rs. 200.", effect: { kind: "moveTo", pos: 0, awardGo: true } },
  { id: "q14", text: "Take a trip to Allama Iqbal International Airport. If you pass GO, collect your salary.", effect: { kind: "moveTo", pos: 15, awardGo: true } },
  { id: "q15", text: "Advance to the nearest airport and pay the owner DOUBLE the usual fee.", effect: { kind: "nearestAirport" } },
  { id: "q16", text: "Advance to the nearest utility. Pay 10× your dice roll if owned.", effect: { kind: "nearestUtility" } },
  { id: "q17", text: "Go back 3 spaces.", effect: { kind: "moveBy", steps: -3 } },
  { id: "q18", text: "Stock market gains on the PSX. Collect Rs. 80.", effect: { kind: "collect", amount: 80 } },
  { id: "q19", text: "Dividend from a textile mill. Collect Rs. 45.", effect: { kind: "collect", amount: 45 } },
  { id: "q20", text: "Speeding ticket on the M-2 Motorway. Pay Rs. 20.", effect: { kind: "pay", amount: 20 } },
  { id: "q21", text: "Mobile data overcharge. Pay Rs. 12.", effect: { kind: "pay", amount: 12 } },
  { id: "q22", text: "Crypto bet went wrong. Pay Rs. 100.", effect: { kind: "pay", amount: 100 } },
  { id: "q23", text: "Crypto bet paid off handsomely. Collect Rs. 100.", effect: { kind: "collect", amount: 100 } },
  { id: "q24", text: "Your startup secured VC funding. Collect Rs. 200.", effect: { kind: "collect", amount: 200 } },
  { id: "q25", text: "Annual audit penalty. Pay Rs. 35.", effect: { kind: "pay", amount: 35 } },
  { id: "q26", text: "Cricket bet won — Pakistan beat India! Collect Rs. 50.", effect: { kind: "collect", amount: 50 } },
  { id: "q27", text: "Loadshedding spoiled your cold storage. Pay Rs. 30.", effect: { kind: "pay", amount: 30 } },
  { id: "q28", text: "Solar panels installed — big energy savings. Collect Rs. 25.", effect: { kind: "collect", amount: 25 } },
  { id: "q29", text: "Advance to Lahore, the heart of Pakistan.", effect: { kind: "moveTo", pos: 32, awardGo: true } },
  { id: "q30", text: "Advance to DHA Lahore — a luxury plot opportunity.", effect: { kind: "moveTo", pos: 39, awardGo: true } },
  { id: "q31", text: "Elected to the chamber of commerce — collect Rs. 10 from each player.", effect: { kind: "collectFromEach", amount: 10 } },
  { id: "q32", text: "Bank loan approved. Collect Rs. 120.", effect: { kind: "collect", amount: 120 } },
  { id: "q33", text: "Bank loan instalment due. Pay Rs. 70.", effect: { kind: "pay", amount: 70 } },
  { id: "q34", text: "Property tax reassessment. Pay Rs. 25 per developed plot and Rs. 100 per Corporate Tower.", effect: { kind: "repairs", perStageEarly: 25, perTower: 100 } },
  { id: "q35", text: "Fuel subsidy refund. Collect Rs. 30.", effect: { kind: "collect", amount: 30 } },
  { id: "q36", text: "Petrol price hike eats your budget. Pay Rs. 22.", effect: { kind: "pay", amount: 22 } },
  { id: "q37", text: "Won a luxury car in a lucky draw — you sell it. Collect Rs. 90.", effect: { kind: "collect", amount: 90 } },
  { id: "q38", text: "Customs seized your imported goods. Pay Rs. 60.", effect: { kind: "pay", amount: 60 } },
  { id: "q39", text: "Featured in Forbes 30 Under 30. Collect Rs. 100.", effect: { kind: "collect", amount: 100 } },
  { id: "q40", text: "Wedding hall booking deposit. Pay Rs. 40.", effect: { kind: "pay", amount: 40 } },
  { id: "q41", text: "Rental income from a city flat. Collect Rs. 35.", effect: { kind: "collect", amount: 35 } },
  { id: "q42", text: "CDA fine for unapproved construction. Pay Rs. 50.", effect: { kind: "pay", amount: 50 } },
  { id: "q43", text: "Advance to Gwadar — a port investment beckons.", effect: { kind: "moveTo", pos: 27, awardGo: true } },
  { id: "q44", text: "Advance to Murree for the holiday season.", effect: { kind: "moveTo", pos: 29, awardGo: true } },
  { id: "q45", text: "Currency devaluation hits your reserves. Pay Rs. 45.", effect: { kind: "pay", amount: 45 } },
  { id: "q46", text: "Export order from the EU. Collect Rs. 110.", effect: { kind: "collect", amount: 110 } },
  { id: "q47", text: "Patent royalties paid out. Collect Rs. 70.", effect: { kind: "collect", amount: 70 } },
  { id: "q48", text: "Lawyer's retainer fee. Pay Rs. 30.", effect: { kind: "pay", amount: 30 } },
  { id: "q49", text: "Inheritance plot sold at a premium. Collect Rs. 150.", effect: { kind: "collect", amount: 150 } },
  { id: "q50", text: "Donate generously to flood relief. Pay Rs. 25.", effect: { kind: "pay", amount: 25 } },
  { id: "q51", text: "Insurance claim approved. Collect Rs. 55.", effect: { kind: "collect", amount: 55 } },
  { id: "q52", text: "Late tax-filing surcharge. Pay Rs. 18.", effect: { kind: "pay", amount: 18 } },
  { id: "q53", text: "Frequent flyer — advance to the nearest airport and pay DOUBLE.", effect: { kind: "nearestAirport" } },
  { id: "q54", text: "Festival sale profits roll in. Collect Rs. 40.", effect: { kind: "collect", amount: 40 } },
  { id: "q55", text: "Catch a tailwind — move forward 3 spaces.", effect: { kind: "moveBy", steps: 3 } },
  { id: "q56", text: "Government incentive for IT exports. Collect Rs. 85.", effect: { kind: "collect", amount: 85 } },
];

/** Awami Fund — the "Community Chest"-style deck. Personal & community events. */
export const AWAMI: Card[] = [
  { id: "a1", text: "Eid bonus received. Collect Rs. 50.", effect: { kind: "collect", amount: 50 } },
  { id: "a2", text: "Wedding expenses incurred. Pay Rs. 80.", effect: { kind: "pay", amount: 80 } },
  { id: "a3", text: "Scholarship awarded to your child. Collect Rs. 30.", effect: { kind: "collect", amount: 30 } },
  { id: "a4", text: "Family business profits. Collect Rs. 60.", effect: { kind: "collect", amount: 60 } },
  { id: "a5", text: "Medical expenses for a relative. Pay Rs. 40.", effect: { kind: "pay", amount: 40 } },
  { id: "a6", text: "Inheritance received. Collect Rs. 100.", effect: { kind: "collect", amount: 100 } },
  { id: "a7", text: "Business investment pays off. Collect Rs. 90.", effect: { kind: "collect", amount: 90 } },
  { id: "a8", text: "Charity donation requested for the masjid. Pay Rs. 20.", effect: { kind: "pay", amount: 20 } },
  { id: "a9", text: "Agricultural subsidy granted. Collect Rs. 45.", effect: { kind: "collect", amount: 45 } },
  { id: "a10", text: "Utility rebate approved. Collect Rs. 15.", effect: { kind: "collect", amount: 15 } },
  { id: "a11", text: "Hospital stay — surgery bill. Pay Rs. 70.", effect: { kind: "pay", amount: 70 } },
  { id: "a12", text: "Won second prize in a baking contest. Collect Rs. 10.", effect: { kind: "collect", amount: 10 } },
  { id: "a13", text: "Sadqa charity drive — pay Rs. 5 to every other player.", effect: { kind: "payEach", amount: 5 } },
  { id: "a14", text: "You hosted a successful charity gala — collect Rs. 15 from each player.", effect: { kind: "collectFromEach", amount: 15 } },
  { id: "a15", text: "Zakat due on your savings. Pay Rs. 35.", effect: { kind: "pay", amount: 35 } },
  { id: "a16", text: "Pension arrears released. Collect Rs. 55.", effect: { kind: "collect", amount: 55 } },
  { id: "a17", text: "School fees for the term. Pay Rs. 25.", effect: { kind: "pay", amount: 25 } },
  { id: "a18", text: "Sold grandmother's gold bangles. Collect Rs. 80.", effect: { kind: "collect", amount: 80 } },
  { id: "a19", text: "Home repairs by plumber & electrician. Pay Rs. 30 per developed plot, Rs. 100 per Tower.", effect: { kind: "repairs", perStageEarly: 30, perTower: 100 } },
  { id: "a20", text: "Community development grant. Collect Rs. 40.", effect: { kind: "collect", amount: 40 } },
  { id: "a21", text: "Birth of a child — sweets for everyone! Pay Rs. 6 to each player.", effect: { kind: "payEach", amount: 6 } },
  { id: "a22", text: "Won a court case — costs awarded to you. Collect Rs. 70.", effect: { kind: "collect", amount: 70 } },
  { id: "a23", text: "Lost a court case — pay damages. Pay Rs. 70.", effect: { kind: "pay", amount: 70 } },
  { id: "a24", text: "Get out of Central Lockup free. Keep this card until needed.", effect: { kind: "jailFree" } },
  { id: "a25", text: "NAB calls you in for questioning. Go to Central Lockup.", effect: { kind: "goToJail" } },
  { id: "a26", text: "Advance to GO. Collect Rs. 200.", effect: { kind: "moveTo", pos: 0, awardGo: true } },
  { id: "a27", text: "Bank error in your favour. Collect Rs. 20.", effect: { kind: "collect", amount: 20 } },
  { id: "a28", text: "Income tax notice served. Pay Rs. 50.", effect: { kind: "pay", amount: 50 } },
  { id: "a29", text: "Eidi from the elders. Collect Rs. 12.", effect: { kind: "collect", amount: 12 } },
  { id: "a30", text: "Qurbani expenses for Eid-ul-Adha. Pay Rs. 25.", effect: { kind: "pay", amount: 25 } },
  { id: "a31", text: "Your crops did very well this season. Collect Rs. 65.", effect: { kind: "collect", amount: 65 } },
  { id: "a32", text: "Crop failure due to drought. Pay Rs. 45.", effect: { kind: "pay", amount: 45 } },
  { id: "a33", text: "Remittance from family in Dubai. Collect Rs. 75.", effect: { kind: "collect", amount: 75 } },
  { id: "a34", text: "Hajj savings withdrawn for the journey. Pay Rs. 60.", effect: { kind: "pay", amount: 60 } },
  { id: "a35", text: "Won a kabaddi tournament prize. Collect Rs. 15.", effect: { kind: "collect", amount: 15 } },
  { id: "a36", text: "Repair the family tractor. Pay Rs. 35.", effect: { kind: "pay", amount: 35 } },
  { id: "a37", text: "Sold buffalo milk all year round. Collect Rs. 30.", effect: { kind: "collect", amount: 30 } },
  { id: "a38", text: "Gas bill arrears cleared. Pay Rs. 22.", effect: { kind: "pay", amount: 22 } },
  { id: "a39", text: "Microfinance loan approved. Collect Rs. 40.", effect: { kind: "collect", amount: 40 } },
  { id: "a40", text: "Microfinance repayment due. Pay Rs. 30.", effect: { kind: "pay", amount: 30 } },
  { id: "a41", text: "Dowry savings matured. Collect Rs. 90.", effect: { kind: "collect", amount: 90 } },
  { id: "a42", text: "House renovation before the guests arrive. Pay Rs. 50.", effect: { kind: "pay", amount: 50 } },
  { id: "a43", text: "Government laptop scheme winner. Collect Rs. 18.", effect: { kind: "collect", amount: 18 } },
  { id: "a44", text: "Mobile phone stolen at the bazaar. Pay Rs. 13.", effect: { kind: "pay", amount: 13 } },
  { id: "a45", text: "Profit from your poultry farm. Collect Rs. 35.", effect: { kind: "collect", amount: 35 } },
  { id: "a46", text: "Veterinary bills for the livestock. Pay Rs. 20.", effect: { kind: "pay", amount: 20 } },
  { id: "a47", text: "Won the neighbourhood committee draw. Collect Rs. 25.", effect: { kind: "collect", amount: 25 } },
  { id: "a48", text: "Housing society maintenance charges. Pay Rs. 16.", effect: { kind: "pay", amount: 16 } },
  { id: "a49", text: "Pension fund maturity. Collect Rs. 120.", effect: { kind: "collect", amount: 120 } },
  { id: "a50", text: "Funeral expenses for a relative. Pay Rs. 40.", effect: { kind: "pay", amount: 40 } },
  { id: "a51", text: "An old debt is repaid to you. Collect Rs. 50.", effect: { kind: "collect", amount: 50 } },
  { id: "a52", text: "Generously tip your staff on Eid. Pay Rs. 9 to each player.", effect: { kind: "payEach", amount: 9 } },
  { id: "a53", text: "Refund from an online shop. Collect Rs. 14.", effect: { kind: "collect", amount: 14 } },
  { id: "a54", text: "Property documents notarised. Pay Rs. 12.", effect: { kind: "pay", amount: 12 } },
  { id: "a55", text: "Rooftop garden produce sold. Collect Rs. 11.", effect: { kind: "collect", amount: 11 } },
  { id: "a56", text: "Neighbours collected to help rebuild after a fire — collect Rs. 12 from each player.", effect: { kind: "collectFromEach", amount: 12 } },
];
